package:
  name: danbing-tk
  version: "2025.03.06"

source:
  path: ./

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - libstdcxx-ng
    - libgcc-ng
  run:
    - libgcc-ng
    - libstdcxx-ng
test:
  commands:
    - danbing-tk
    - danbing-tk-pred
    - genPanKmers
    - ktools
    - vntr2kmers_thread
about:
   home: https://github.com/ChaissonLab/danbing-tk
   summary: Toolkit for VNTR genotyping and repeat-pan genome graph construction
   license: BSD-3-Clause
