package:
  name: danbing-tk
  version: "1.3.3"

source:
  path: ./danbing-tk

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - libstdcxx-ng
    - libgcc-ng
  run:
    - libgcc-ng
    - libstdcxx-ng
